DROP TABLE Executions;
DROP TABLE Alumni_Assignments;
DROP TABLE Alumni_Subjects;
DROP TABLE Alumni;
DROP TABLE Assignment_Code_Templates;
DROP TABLE Assignment_Examples;
DROP TABLE Assignments;
DROP TABLE Subjects;
DROP TABLE Professors;
