# syntax=docker/dockerfile:1
FROM golang:1.19.3 AS builder

WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o temporal-worker ./cmd/worker/main.go

FROM judge0/compilers:latest AS executor

WORKDIR /app

COPY --from=builder /app/temporal-worker .

# Run
CMD ["./temporal-worker"]