version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile.server
    restart: unless-stopped
    environment:
      - TEMPORALITE_HOST_PORT=temporalite:7233
    depends_on:
    - worker
    - temporalite
    ports:
      - "8080:8080"

  worker:
    build:
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    environment:
      - TEMPORALITE_HOST_PORT=temporalite:7233
    depends_on:
      - temporalite

  temporalite:
    build: "https://github.com/temporalio/temporalite.git"
    ports:
      - "8233"