# syntax=docker/dockerfile:1

FROM golang:1.19.3

WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o executor-server ./cmd/server/main.go

EXPOSE 8080

# Run
CMD ["./executor-server"]
