// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Execution struct {
	ID       string `json:"id"`
	Language string `json:"language"`
	Code     string `json:"code"`
}

type ExecutionResult struct {
	CompilationResult string `json:"compilationResult"`
	Finished          bool   `json:"finished"`
	Error             bool   `json:"error"`
}

type NewExecution struct {
	Language string `json:"language"`
	Code     string `json:"code"`
}
