// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlumniSubject = "alumni_subjects"

// AlumniSubject mapped from table <alumni_subjects>
type AlumniSubject struct {
	AlumniID  int32 `gorm:"column:alumni_id;primaryKey" json:"alumni_id"`
	SubjectID int32 `gorm:"column:subject_id;primaryKey" json:"subject_id"`
}

// TableName AlumniSubject's table name
func (*AlumniSubject) TableName() string {
	return TableNameAlumniSubject
}
