// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlumni = "alumni"

// Alumni mapped from table <alumni>
type Alumni struct {
	AlumniID       int32  `gorm:"column:alumni_id;primaryKey;autoIncrement:true" json:"alumni_id"`
	FirstName      string `gorm:"column:first_name" json:"first_name"`
	LastName       string `gorm:"column:last_name" json:"last_name"`
	Email          string `gorm:"column:email" json:"email"`
	GraduationYear int32  `gorm:"column:graduation_year" json:"graduation_year"`
}

// TableName Alumni's table name
func (*Alumni) TableName() string {
	return TableNameAlumni
}
