// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlumniAssignment = "alumni_assignments"

// AlumniAssignment mapped from table <alumni_assignments>
type AlumniAssignment struct {
	AlumniID     int32  `gorm:"column:alumni_id;primaryKey" json:"alumni_id"`
	AssignmentID int32  `gorm:"column:assignment_id;primaryKey" json:"assignment_id"`
	Grade        string `gorm:"column:grade" json:"grade"`
}

// TableName AlumniAssignment's table name
func (*AlumniAssignment) TableName() string {
	return TableNameAlumniAssignment
}
