// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAssignment = "assignments"

// Assignment mapped from table <assignments>
type Assignment struct {
	AssignmentID          int32  `gorm:"column:assignment_id;primaryKey;autoIncrement:true" json:"assignment_id"`
	AssignmentTitle       string `gorm:"column:assignment_title" json:"assignment_title"`
	AssignmentDescription string `gorm:"column:assignment_description" json:"assignment_description"`
	SubjectID             int32  `gorm:"column:subject_id" json:"subject_id"`
	ProfessorID           int32  `gorm:"column:professor_id" json:"professor_id"`
}

// TableName Assignment's table name
func (*Assignment) TableName() string {
	return TableNameAssignment
}
