// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAssignmentExample = "assignment_examples"

// AssignmentExample mapped from table <assignment_examples>
type AssignmentExample struct {
	ID                 int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AssignmentID       int32          `gorm:"column:assignment_id" json:"assignment_id"`
	ExampleTitle       string         `gorm:"column:example_title" json:"example_title"`
	ExampleDescription string         `gorm:"column:example_description" json:"example_description"`
	CreatedAt          time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName AssignmentExample's table name
func (*AssignmentExample) TableName() string {
	return TableNameAssignmentExample
}
