// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExecution = "executions"

// Execution mapped from table <executions>
type Execution struct {
	ExecutionID  int32  `gorm:"column:execution_id;primaryKey;autoIncrement:true" json:"execution_id"`
	Language     string `gorm:"column:language" json:"language"`
	WorkflowID   string `gorm:"column:workflow_id" json:"workflow_id"`
	RunID        string `gorm:"column:run_id" json:"run_id"`
	Code         string `gorm:"column:code" json:"code"`
	AssignmentID int32  `gorm:"column:assignment_id" json:"assignment_id"`
}

// TableName Execution's table name
func (*Execution) TableName() string {
	return TableNameExecution
}
