// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSubject = "subjects"

// Subject mapped from table <subjects>
type Subject struct {
	SubjectID   int32  `gorm:"column:subject_id;primaryKey;autoIncrement:true" json:"subject_id"`
	SubjectName string `gorm:"column:subject_name" json:"subject_name"`
	Semester    int32  `gorm:"column:semester" json:"semester"`
	ProfessorID int32  `gorm:"column:professor_id" json:"professor_id"`
}

// TableName Subject's table name
func (*Subject) TableName() string {
	return TableNameSubject
}
